import fs from 'node:fs';
import MarkdownIt from 'markdown-it';
const root=new URL('../../output/rf/',import.meta.url);
const md=fs.readFileSync(new URL('README.md',root),'utf8');
const render=new MarkdownIt({html:false,linkify:true,typographer:true});
const old=render.renderer.rules.table_open||(()=>'<table>');
render.renderer.rules.table_open=(...args)=>'<div class="table-scroll">'+old(...args);
render.renderer.rules.table_close=()=>'</table></div>';
const html=`<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>nRF Canon Remote · openEMS 天线计算 · 2026-09-24</title><style>
:root{color-scheme:light}*{box-sizing:border-box}body{margin:0;background:#f4f2ed;color:#26372f;font:16px/1.85 -apple-system,BlinkMacSystemFont,"PingFang SC","Microsoft YaHei",sans-serif}main{max-width:1080px;margin:40px auto;padding:48px 56px;background:#fff;border:1px solid #dfe3dc;border-radius:20px}header{font-size:12px;letter-spacing:.12em;color:#697b70}h1{font-size:32px;line-height:1.45;margin:12px 0 22px}h2{font-size:23px;margin-top:44px;padding-top:20px;border-top:1px solid #dfe3dc}h3{font-size:18px;margin-top:26px}a{color:#246953;text-underline-offset:3px}p,li{overflow-wrap:anywhere}blockquote{margin:24px 0;padding:16px 22px;background:#fbf4e9;border-left:4px solid #b77d42;border-radius:4px}blockquote p{margin:0}img{display:block;max-width:100%;height:auto;margin:24px auto}pre{overflow:auto;background:#f3f5f1;border:1px solid #e2e6df;padding:18px;border-radius:8px;line-height:1.65;font-size:14px}code{font-family:ui-monospace,SFMono-Regular,monospace;font-size:.9em}.table-scroll{overflow-x:auto;margin:22px 0}table{border-collapse:collapse;min-width:640px;width:100%;font-size:14px}th,td{padding:11px 14px;text-align:left;border-bottom:1px solid #e4e8e1}th{background:#ecf1eb;white-space:nowrap}td{vertical-align:top}ul,ol{padding-left:24px}footer{font-size:13px;color:#697b70;margin-top:40px}@media(max-width:700px){main{margin:12px;padding:24px 20px;border-radius:12px}h1{font-size:26px}h2{font-size:21px}body{font-size:15px}}@media print{body{background:white}main{margin:0;border:0;padding:0;max-width:none}.table-scroll{overflow:visible}table{min-width:0}a{color:inherit}h2,h3{break-after:avoid}img,table{break-inside:avoid}}
</style></head><body><main><header>NRF CANON REMOTE / RF STUDY / 2026-09-24</header>${render.render(md)}<footer>openEMS 0.37.0 · CSXCAD 0.7.0 · 初步计算，非样机实测。</footer></main></body></html>`;
fs.writeFileSync(new URL('antenna-20260923.html',root),html);
console.log('Built output/rf/antenna-20260923.html');
