import fs from 'node:fs';
import {build} from 'esbuild';
const data=JSON.parse(fs.readFileSync('output/model-data.json','utf8'));
if(data.report.interference_failures.length)throw new Error('Refusing to package a model with unresolved interference');
const c=data.config;
const fields={CORNER_R:c.pcb.corner_notches.radius,LOCATOR_R:c.pcb.corner_notches.radius-c.shell.corner_locators.radial_clearance,CORNER_GAP:c.shell.corner_locators.radial_clearance,LED_Y:c.led[1],MOUNTS:c.mounts.length,REAR_WIDTH:c.shell.width-2*c.shell.rear_taper.inset,RING_Y:c.ring_center[1],ROUND_Y:c.keys.find(k=>k.id==='key_circle1').switches[0][1]+c.keys.find(k=>k.id==='key_circle1').translation[1],END_Y:-c.shell.length/2,VERSION:c.version,LENGTH:c.shell.length,WIDTH:c.shell.width,DEPTH:c.shell.depth,SHORTER:140-c.shell.length,KEYS:data.report.keycap_count,SWITCHES:data.report.switch_count,PCB_LENGTH:(c.pcb.top-c.pcb.tongue_end).toFixed(2),PCB_WIDTH:c.pcb.width.toFixed(2),PCB_BOTTOM:c.pcb.z_bottom.toFixed(2),PCB_TOP:(c.pcb.z_bottom+c.pcb.thickness).toFixed(2),TONGUE_END:c.pcb.tongue_end,TONGUE_EXT:c.pcb.body_bottom-c.pcb.tongue_end,USB_FRONT:c.usb.front,USB_Z:data.report.usb.center_z.toFixed(2),USB_PROTRUSION:data.report.usb.protrusion_mm,BATTERY_MODEL:c.battery.model,BATTERY_CAPACITY:c.battery.capacity_mah,BATTERY_SIZE:c.battery.size.join(' × '),PAIR_CHECKS:Object.keys(data.report.interference_mm3).length};
const result=await build({entryPoints:['scripts/viewer.js'],bundle:true,minify:true,format:'iife',write:false,legalComments:'inline'});
let template=fs.readFileSync('scripts/preview.template.html','utf8').replace(/\{\{([A-Z_]+)\}\}/g,(_,key)=>{if(!(key in fields))throw Error(key);return fields[key]});
fs.writeFileSync('output/preview.html',template.replace('__MODEL_DATA__',()=>JSON.stringify(data)).replace('__VIEWER_BUNDLE__',()=>result.outputFiles[0].text.replace(/<\/script/gi,'<\\/script')));
console.log('Built self-contained output/preview.html — revision '+c.version);
